### ISSUE TITLE
ValueError: text_id not found in id_map when loading an index from disk with GPTFaissIndex.load_from_disk 

### ISSUE THREAD

**Issue by kyang6** [jerryjliu/gpt_index#124]
In the example notebook, FaissIndexDemo.ipynb when loading an index from disk and querying the index the following error is thrown:

```File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/gpt_index/indices/query/query_runner.py:79, in QueryRunner.query(self, query_str, index_struct)
     76 if not query_obj._llm_predictor_set:
     77     query_obj.set_llm_predictor(self._llm_predictor)
---> 79 return query_obj.query(query_str, verbose=self._verbose)
...
--> 180         raise ValueError("text_id not found in id_map")
    181     int_id = self.id_map[text_id]
    182     if int_id not in self.nodes_dict:

ValueError: text_id not found in id_map```

Building a new index and querying it works.

**Comment by jerryjliu** [comment]
nice catch, thanks! i'll have a fix soon

**Comment by jerryjliu** [comment]
Hmm wait I'm not able to repro. Can you send me your index_faiss.json and the command you're using?

**Comment by kyang6** [comment]
Yeah! It might be an issue with the versions of packages. Here's what I have
[requirements.txt](https://github.com/jerryjliu/gpt_index/files/10296840/requirements.txt)
_faiss.txt)

I am running on Python 3.10.6

I changed the file type to txt to share the file here.
[index_faiss.txt](https://github.com/jerryjliu/gpt_index/files/10296833/index

Here is the order of commands I am running:
```
import faiss
# dimensions of text-ada-embedding-002
d = 1536 
faiss_index = faiss.IndexFlatL2(d)
from gpt_index import GPTFaissIndex, SimpleDirectoryReader
from IPython.display import Markdown, display

# load index from disk
index = GPTFaissIndex.load_from_disk(
    'index_faiss.json', 
    faiss_index_save_path="index_faiss_core.index"
)

response = index.query("what is the company name?", verbose=True)
```

And the full error output:
<img width="1175" alt="Screenshot 2022-12-23 at 11 39 53 AM" src="https://user-images.githubusercontent.com/15041780/209392924-5dd688de-6c62-4966-abe2-c1870ee0b581.png">

**Comment by jerryjliu** [comment]
Update: thanks for this. I've repro'ed the issue and I have an idea of what the bug fix is. Will put out soon!

**Comment by jerryjliu** [comment]
@kyang6 I've merged in #128 which will resolve this issue. I'll have a new gpt-index pypi package lined up for tomorrow morning, but in the meantime if you want to use the latest fixes, you can clone the repo and just do `pip install -e .`. Thanks 🙏 for surfacing!

**Comment by kyang6** [comment]
Amazing!!

Also, thank you for creating gpt_index!! This is so cool :)

**Comment by VivaLaPanda** [comment]
This seems to have been reintroduced?

```
>>> import faiss
 import OpenAIEmbedding, PromptHelper
from langchain.llms import AzureOpenAI>>> from gpt_index import GPTFaissIndex, SimpleDirectoryReader, LLMPredictor
>>> from gpt_index import OpenAIEmbedding, PromptHelper
>>> from langchain.llms import AzureOpenAI
>>> d = 4096
>>> faiss_index = faiss.IndexFlatL2(d)
>>> llm = AzureOpenAI(deployment_name="text-davinci-003", model_name="text-davinci-003")
>>> llm_predictor = LLMPredictor(llm=llm)
>>> embeddings = OpenAIEmbedding(deployment_name='text-similarity-curie-001')
PTFaissIndex.load_from_disk('docs.json', faiss_index=faiss_index, llm_predictor=llm_predictor, embed_model=embeddings)
2023-01-27 15:43:23.689518: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-27 15:43:23.689546: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> index = GPTFaissIndex.load_from_disk('docs.json', faiss_index=faiss_index, llm_predictor=llm_predictor, embed_model=embeddings)
>>> index.query("Any way to get the product / items list in Stripe via API?")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/indices/base.py", line 333, in query
    return query_runner.query(query_str, self._index_struct)
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/indices/query/query_runner.py", line 111, in query
    return query_obj.query(query_str, verbose=self._verbose)
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/token_counter/token_counter.py", line 54, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/indices/query/base.py", line 274, in query
    response = self._query(query_str, verbose=verbose)
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/indices/query/base.py", line 248, in _query
    tuples = self.get_nodes_and_similarities_for_response(
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/indices/query/base.py", line 226, in get_nodes_and_similarities_for_response
    nodes = self._get_nodes_for_response(
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/indices/query/vector_store/faiss.py", line 75, in _get_nodes_for_response
    top_k_nodes = self._index_struct.get_nodes(node_idxs)
  File "/pay/src/zoolander/vendor3/lib/python3.8/site-packages/gpt_index/data_structs/data_structs.py", line 202, in get_nodes
    raise ValueError("text_id not found in id_map")
ValueError: text_id not found in id_map
```
