### ISSUE TITLE
Error when constructing tree index async

### ISSUE THREAD

**Issue by Kav-K** [jerryjliu/gpt_index#532]
When constructing a GPTTreeIndex with use_async=True:

```
INFO:root:> Building index from nodes: 21 chunks
Traceback (most recent call last):
  File "/home/gptbot/models/index_model.py", line 314, in set_file_index
    index = await self.loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/gptbot/models/index_model.py", line 173, in index_file
    index = GPTTreeIndex(document, embed_model=embed_model, use_async=True)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/tree/base.py", line 74, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 278, in build_index_from_documents
    return self._build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/tree/base.py", line 124, in _build_index_from_documents
    index_graph = index_builder.build_from_text(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/common/tree/base.py", line 83, in build_from_text
    root_nodes = self.build_index_from_nodes(all_nodes, all_nodes)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/common/tree/base.py", line 118, in build_index_from_nodes
    outputs: List[Tuple[str, str]] = run_async_tasks(tasks)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/async_utils.py", line 12, in run_async_tasks
    outputs: List[Any] = asyncio.run(_gather())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/async_utils.py", line 10, in _gather
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/langchain_helpers/chain_wrapper.py", line 182, in apredict
    llm_prediction = await self._apredict(prompt, **prompt_args)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/langchain_helpers/chain_wrapper.py", line 168, in _apredict
    llm_prediction = await llm_chain.apredict(**full_prompt_args)
AttributeError: 'LLMChain' object has no attribute 'apredict'


```

**Comment by jerryjliu** [comment]
@Kav-K you may have to upgrade your langchain version

**Comment by Kav-K** [comment]
I'm using the old gpt-index imports instead of llama-index, is this a problem? My langchain is up to date

**Comment by Kav-K** [comment]
I notice that in the new async notebooks the import is
```
from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
```
For my LLMPredictor imports currently, I have
```
from gpt_index import LLMPredictor
```

**Comment by jerryjliu** [comment]
hmm that shouldn't be an issue i think. what version of langchain are you on?

**Comment by Kav-K** [comment]
I updated langchain to the latest and I get

```
The moderation service is ready.
Commands synced
application/pdf
Traceback (most recent call last):
  File "/home/gptbot/models/index_model.py", line 317, in set_file_index
    index = self.index_file(temp_path, embedding_model)
  File "/home/gptbot/models/index_model.py", line 172, in index_file
    index = GPTSimpleVectorIndex(document, embed_model=embed_model, use_async=True)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/vector_store/vector_indices.py", line 57, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/vector_store/base.py", line 62, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 278, in build_index_from_documents
    return self._build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/vector_store/base.py", line 202, in _build_index_from_documents
    run_async_tasks(tasks)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/async_utils.py", line 12, in run_async_tasks
    outputs: List[Any] = asyncio.run(_gather())
  File "/usr/lib/python3.9/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
/home/gptbot/models/index_model.py:327: RuntimeWarning: coroutine 'run_async_tasks.<locals>._gather' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/gptbot/models/index_model.py:327: RuntimeWarning: coroutine 'GPTVectorStoreIndex._async_add_document_to_index' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

Can use_async=True not be used when the function that's calling it is already async?

**Comment by jerryjliu** [comment]
@Kav-K this is interesting. To be honest I'm still looking into this, we may need to make changes in the core codebase to support this. In the meantime have you tried `nest_asyncio`? https://stackoverflow.com/questions/55409641/asyncio-run-cannot-be-called-from-a-running-event-loop-when-using-jupyter-no

**Comment by Kav-K** [comment]
No worries, I've managed to workaround it but it seems that use_async=True can't be called in an already async function

**Comment by iraadit** [comment]
Hi @Kav-K , how did you work around it?
