### ISSUE TITLE
Building vector index fails when there's a single long line in a document (v0.4.14)

### ISSUE THREAD

**Issue by kenn** [jerryjliu/gpt_index#579]
To be precise, in Japanese characters, 600 chars (or 1,800 bytes in UTF-8) are ok, but 601 chars (1,803 bytes) fail. Note that the token count in CJK languages seems to be very different (words vs chars), so it may not happen in other languages.

You can reproduce it by copy-paste the following series of "あ", extend it to 600-601 chars and save as `600.txt` and `601.txt`. Make sure it is a single line and doesn't have any linefeeds. `600.txt` will build but `601.txt` won't.

```
ああああああああああ
```

Error / stack trace

```py
2023-03-01 12:32:27.848 processing upload and building index
2023-03-01 12:32:28.501 error_code=None error_message="[''] is not valid under any of the given schemas - 'input'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-01 12:32:31.707 error_code=None error_message="[''] is not valid under any of the given schemas - 'input'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-01 12:32:33.227 error_code=None error_message="[''] is not valid under any of the given schemas - 'input'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-01 12:32:37.419 error_code=None error_message="[''] is not valid under any of the given schemas - 'input'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-01 12:32:39.388 error_code=None error_message="[''] is not valid under any of the given schemas - 'input'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-01 12:32:47.986 error_code=None error_message="[''] is not valid under any of the given schemas - 'input'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-01 12:32:47.987 Uncaught app exception
Traceback (most recent call last):
  File "/Users/.../.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 147, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, engine=engine).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/.../.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(

openai.error.InvalidRequestError: [''] is not valid under any of the given schemas - 'input'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  ...
  File "/Users/.../test.py", line 93, in build_index
    index = GPTSimpleVectorIndex(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/vector_indices.py", line 57, in __init__
    super().__init__(
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 62, in __init__
    super().__init__(
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 278, in build_index_from_documents
    return self._build_index_from_documents(documents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 205, in _build_index_from_documents
    self._add_document_to_index(index_struct, d)
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 181, in _add_document_to_index
    embedding_results = self._get_node_embedding_results(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 101, in _get_node_embedding_results
    result_ids, result_embeddings = self._embed_model.get_queued_text_embeddings()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 151, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 260, in _get_text_embeddings
    embeddings = get_embeddings(texts, engine=engine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 363, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1693b53d0 state=finished raised InvalidRequestError>]
```

**Comment by jerryjliu** [comment]
@kenn thanks for surfacing! will take a look very soon

**Comment by jerryjliu** [comment]
@kenn i just tested this, for some reason it's working for me (i tried 600 chars and 601 chars). could you confirm if this is still a bug on your end?

**Comment by kenn** [comment]
Ah right, 601 chars are no longer an issue, but if you extend it longer, it still causes an error. Here's one with 1500 chars.

[1500.txt](https://github.com/jerryjliu/gpt_index/files/10890478/1500.txt)

It seems like a bug in the openai lib?

```py
2023-03-05 09:16:48.287 Uncaught app exception
Traceback (most recent call last):
  File "/Users/___/.venv/lib/python3.11/site-packages/openai/openai_object.py", line 59, in __getattr__
    return self[k]
           ~~~~^^^
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 147, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, engine=engine).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 38, in create
    for data in response.data:
                ^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/openai/openai_object.py", line 61, in __getattr__
    raise AttributeError(*err.args)
AttributeError: data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/___/.venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/___/___/___.py", line 18, in <module>
    process_upload(uploaded_file)
  File "/Users/___/___/___.py", line 56, in process_upload
    build_index()
  File "/Users/___/___/___.py", line 55, in build_index
    index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/vector_indices.py", line 83, in __init__
    super().__init__(
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 62, in __init__
    super().__init__(
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 278, in build_index_from_documents
    return self._build_index_from_documents(documents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 205, in _build_index_from_documents
    self._add_document_to_index(index_struct, d)
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 181, in _add_document_to_index
    embedding_results = self._get_node_embedding_results(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 101, in _get_node_embedding_results
    result_ids, result_embeddings = self._embed_model.get_queued_text_embeddings()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 151, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 260, in _get_text_embeddings
    embeddings = get_embeddings(texts, engine=engine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 363, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x127da8e10 state=finished raised AttributeError>]
```

**Comment by jerryjliu** [comment]
> Ah right, 601 chars are no longer an issue, but if you extend it longer, it still causes an error. Here's one with 1500 chars.
> 
> [1500.txt](https://github.com/jerryjliu/gpt_index/files/10890478/1500.txt)
> 
> It seems like a bug in the openai lib?
> 
> ```python
> 2023-03-05 09:16:48.287 Uncaught app exception
> Traceback (most recent call last):
>   File "/Users/___/.venv/lib/python3.11/site-packages/openai/openai_object.py", line 59, in __getattr__
>     return self[k]
>            ~~~~^^^
> KeyError: 'data'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 409, in __call__
>     result = fn(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 147, in get_embeddings
>     data = openai.Embedding.create(input=list_of_text, engine=engine).data
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 38, in create
>     for data in response.data:
>                 ^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/openai/openai_object.py", line 61, in __getattr__
>     raise AttributeError(*err.args)
> AttributeError: data
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/___/.venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
>     exec(code, module.__dict__)
>   File "/Users/___/___/___.py", line 18, in <module>
>     process_upload(uploaded_file)
>   File "/Users/___/___/___.py", line 56, in process_upload
>     build_index()
>   File "/Users/___/___/___.py", line 55, in build_index
>     index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor(),
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/vector_indices.py", line 83, in __init__
>     super().__init__(
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 62, in __init__
>     super().__init__(
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 109, in __init__
>     self._index_struct = self.build_index_from_documents(documents)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
>     f_return_val = f(_self, *args, **kwargs)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 278, in build_index_from_documents
>     return self._build_index_from_documents(documents)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 205, in _build_index_from_documents
>     self._add_document_to_index(index_struct, d)
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 181, in _add_document_to_index
>     embedding_results = self._get_node_embedding_results(
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 101, in _get_node_embedding_results
>     result_ids, result_embeddings = self._embed_model.get_queued_text_embeddings()
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 151, in get_queued_text_embeddings
>     embeddings = self._get_text_embeddings(cur_batch_texts)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 260, in _get_text_embeddings
>     embeddings = get_embeddings(texts, engine=engine)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in wrapped_f
>     return self(f, *args, **kw)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 406, in __call__
>     do = self.iter(retry_state=retry_state)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/___/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 363, in iter
>     raise retry_exc from fut.exception()
> tenacity.RetryError: RetryError[<Future at 0x127da8e10 state=finished raised AttributeError>]
> ```

thanks for the update, will try soon

**Comment by jerryjliu** [comment]
@kenn hmm 1500 and 1501 are working for me as well..

**Comment by kenn** [comment]
Weird, yeah it builds now for me.

It seems that in some cases `openai.Embedding.create(input=list_of_text, engine=engine)` returns `response.data` without the `data` attribute, depending on the server / network status?

In any case, the second error seems like a bug in the OpenAI lib, so I'll close this for now.

Thanks for this great library, @jerryjliu !
