### ISSUE TITLE
Can't mock usage for GPTKnowledgeGraphIndex

### ISSUE THREAD

**Issue by Kav-K** [jerryjliu/gpt_index#589]
Trying to use mocks:
```
partial(
                    GPTKnowledgeGraphIndex,
                    documents,
                    chunk_size_limit=512,
                    max_triplets_per_chunk=2,
                    embed_model=embed_model_mock,
                    llm_predictor=llm_predictor_mock,
                ),
```
Returns
```
Traceback (most recent call last):
  File "/home/gptbot/cogs/search_service_cog.py", line 127, in search_command
    response, refined_text = await self.model.search(
  File "/home/gptbot/models/search_model.py", line 364, in search
    await self.loop.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/knowledge_graph/base.py", line 70, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 109, in __init__
    self._index_struct = self.build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/base.py", line 278, in build_index_from_documents
    return self._build_index_from_documents(documents)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/knowledge_graph/base.py", line 122, in _build_index_from_documents
    triplets = self._extract_triplets(n.get_text())
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/indices/knowledge_graph/base.py", line 87, in _extract_triplets
    response, _ = self._llm_predictor.predict(
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/langchain_helpers/chain_wrapper.py", line 125, in predict
    llm_prediction = self._predict(prompt, **prompt_args)
  File "/usr/local/lib/python3.9/dist-packages/gpt_index/token_counter/mock_chain_wrapper.py", line 103, in _predict
    raise ValueError("Invalid prompt type.")
ValueError: Invalid prompt type.
```

**Comment by jerryjliu** [comment]
thanks for raising - we'll take a look at this soon!

**Comment by jerryjliu** [comment]
should be done now! thanks for all the help @logan-markewich 🥳 🔥
