### ISSUE TITLE
Issues with ChatGPTLLMPredictor

### ISSUE THREAD

**Issue by ankitb82** [jerryjliu/gpt_index#606]
VERSION: 0.4.19

When trying to build an index with llm_predictor as ChatGPTLLMPredictor I get the following error (The key is set by the code as an env var. I even tried setting it via OpenAI.openai_api_key) - 

Traceback (most recent call last):
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/embeddings/openai.py", line 147, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, engine=engine).data
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/openai/api_requestor.py", line 130, in __init__
    self.api_key = key or util.default_api_key()
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://onboard.openai.com for details, or email support@openai.com if you have any questions.

-------

Assuming an existing index is on disk, making a query call just hangs. 

  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/indices/base.py", line 395, in query
    return query_runner.query(query_str, self._index_struct)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/indices/query/query_runner.py", line 120, in query
    return query_obj.query(query_bundle)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/token_counter/token_counter.py", line 55, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 300, in query
    response = self._query(query_bundle)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 262, in _query
    tuples = self.get_nodes_and_similarities_for_response(query_bundle)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/indices/query/base.py", line 233, in get_nodes_and_similarities_for_response
    nodes = self._get_nodes_for_response(
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/indices/query/vector_store/base.py", line 45, in _get_nodes_for_response
    query_embedding = self._embed_model.get_agg_embedding_from_queries(
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/embeddings/base.py", line 79, in get_agg_embedding_from_queries
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/embeddings/base.py", line 79, in <listcomp>
    query_embeddings = [self.get_query_embedding(query) for query in queries]
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/embeddings/base.py", line 68, in get_query_embedding
    query_embedding = self._get_query_embedding(query)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/llama_index/embeddings/openai.py", line 222, in _get_query_embedding
    return get_embedding(query, engine=engine)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/tenacity/__init__.py", line 416, in __call__
    self.sleep(do)
  File "/Users/ankit/miniforge3/lib/python3.10/site-packages/tenacity/nap.py", line 31, in sleep
    time.sleep(seconds)
KeyboardInterrupt

**Comment by logan-markewich** [comment]
@ankitb82  As a sanity check, can you put this at the top of your code?

```
import os
os.environ['OPENAI_API_KEY'] = "your-openai-key"
```

**Comment by logan-markewich** [comment]
If that doesn't work, try generating a new api key

**Comment by madawei2699** [comment]
> @ankitb82 As a sanity check, can you put this at the top of your code? (Obviosuly, use your real key when you copy it in 👍)
> 
> ```
> import os
> os.environ['OPENAI_API_KEY'] = "your-openai-key"
> ```

I try this, but not work, still raise the error.

**Comment by logan-markewich** [comment]
I'm not sure what to think then 🤔 The best advice I can give (in addition to setting that variable at the top of your script) is generating a new key and/or creating a fresh python environment

**Comment by madawei2699** [comment]
Thanks, @logan-markewich when executing the code in the terminal and `export OPENAI_API_KEY=my_key` works!

**Comment by ankitb82** [comment]
> @ankitb82 As a sanity check, can you put this at the top of your code? (Obviosuly, use your real key when you copy it in 👍)
> 
> ```
> import os
> os.environ['OPENAI_API_KEY'] = "your-openai-key"
> ```

This is how the code has been structured from day one. 

I did however try export on the command line and that worked. This means that the code is either forking or executing code in a new context that is not a child of the current python path.

**Comment by jerryjliu** [comment]
sweet! closing for now
