### ISSUE TITLE
No module named 'langchain.chains.prompt_selector'

### ISSUE THREAD

**Issue by Minweiwangaaaa** [jerryjliu/gpt_index#687]
/Users//PycharmProjects/chat/venv/bin/python /Users//PycharmProjects/chat/main.py 
Traceback (most recent call last):
  File "/Users//PycharmProjects/chat/main.py", line 36, in <module>
    from llama_index import GPTSimpleVectorIndex, SimpleDirectoryReader
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/indices/keyword_table/base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/indices/base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/indices/prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/langchain_helpers/chain_wrapper.py", line 13, in <module>
    from llama_index.prompts.base import Prompt
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/prompts/__init__.py", line 3, in <module>
    from llama_index.prompts.base import Prompt
  File "/Users//PycharmProjects/chat/venv/lib/python3.9/site-packages/llama_index/prompts/base.py", line 8, in <module>
    from langchain.chains.prompt_selector import ConditionalPromptSelector
ModuleNotFoundError: No module named 'langchain.chains.prompt_selector'

No module named 'langchain.chains.prompt_selector'

I just updated llama-index, then i got the problem

**Comment by jerryjliu** [comment]
thanks @KenanLi57! yep @Minweiwangaaaa seems like that would solve it. closing this issue for now
