### ISSUE TITLE
Import Error  cannot import name 'AI21' from 'langchain.llms'

### ISSUE THREAD

**Issue by Tobi-De** [jerryjliu/gpt_index#717]
Greetings! thanks for building this, this tool is a gem. As a beginner, I attempted to use it to test some basic stuff, but unfortunately, I encountered an error during my first run. Here's the code I used:

```python
from langchain import OpenAI
from llama_index import (
    GPTSimpleVectorIndex,
    download_loader,
    LLMPredictor,
)

MODEL_TO_USE = "gpt-3.5-turbo"
PDFReader = download_loader("PDFReader")
loader = PDFReader()
documents = loader.load_data(file="boost-your-django-dx.pdf")
llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name=MODEL_TO_USE))

index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor)

# index.save_to_disk('index.json')

while question := input("Question: "):
    print(index.query(question))

```
It seems straightforward, but I encountered the following error:

```shell
Traceback (most recent call last):
  File "/home/tobi/Builds/documate/ai.py", line 3, in <module>
    from llama_index import (
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/__init__.py", line 18, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/keyword_table/base.py", line 16, in <module>
    from llama_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/base.py", line 23, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/indices/prompt_helper.py", line 12, in <module>
    from llama_index.langchain_helpers.chain_wrapper import LLMPredictor
  File "/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/llama_index/langchain_helpers/chain_wrapper.py", line 9, in <module>
    from langchain.llms import AI21
ImportError: cannot import name 'AI21' from 'langchain.llms' (/home/tobi/.cache/pypoetry/virtualenvs/documate-D2J91GFU-py3.11/lib/python3.11/site-packages/langchain/llms/__init__.py)
```

python : 3.11
llama-index : 0.4.26
openai : 0.27.2

**Comment by Tobi-De** [comment]
I don't know exactly how but my issue got fixed, I recreate a new environment and then reinstall all dependencies.
