### ISSUE TITLE
ImportError: cannot import name 'Version' from 'packaging.version'

### ISSUE THREAD

**Issue by Slach** [jerryjliu/gpt_index#91]
requirements.txt
```
gpt_index
numpy==1.23.5
pandas==1.5.2
torch
tensorflow
slack_sdk==3.19.5
```

generate_index.py
```python
import gpt_index
reader = gpt_index.SlackReader(slack_token='XXX)
documents = reader.load_data(channel_ids=[
    'XXX',
    'XXX',
])
index = gpt_index.GPTTreeIndex(documents)
index.save_to_disk('gpt-index.json')
```

python3.10 ./generate_index.py returns error
```
Traceback (most recent call last):
  File "/mnt/c/Users/Slach/Downloads/altinity.staff/src/github.com/altinity/slack-qa/./generate_index.py", line 1, in <module>
    import gpt_index
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/gpt_index/__init__.py", line 9, in <module>
    from gpt_index.indices.keyword_table.base import GPTKeywordTableIndex
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/gpt_index/indices/keyword_table/base.py", line 15, in <module>
    from gpt_index.indices.base import (
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/gpt_index/indices/base.py", line 17, in <module>
    from gpt_index.indices.data_structs import IndexStruct
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/gpt_index/indices/data_structs.py", line 9, in <module>
    from dataclasses_json import DataClassJsonMixin
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/dataclasses_json/__init__.py", line 2, in <module>
    from dataclasses_json.api import (DataClassJsonMixin,
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/dataclasses_json/api.py", line 6, in <module>
    from dataclasses_json.cfg import config, LetterCase  # noqa: F401
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/dataclasses_json/cfg.py", line 5, in <module>
    from marshmallow.fields import Field as MarshmallowField
  File "/home/slach/venv/slack-qa/lib/python3.10/site-packages/marshmallow/__init__.py", line 3, in <module>
    from packaging.version import Version
ImportError: cannot import name 'Version' from 'packaging.version' (/home/slach/venv/slack-qa/lib/python3.10/site-packages/packaging/version.py)
```

could you suggest properly libraries version?

**Comment by jerryjliu** [comment]
Hi @Slach, thanks for surfacing. Could you try `pip install setuptools` or `pip install packaging`, or updating your pip? 

https://stackoverflow.com/questions/42286447/importerror-no-module-named-packaging-version
https://github.com/facebookresearch/TorchRay/issues/4

**Comment by Slach** [comment]
```bash
python3 -m pip install -U pip
pip3 install -U setuptools packaging
```
didn't help
which python version do you use? 3.10 or 3.11 ?

Could you share your `pip3 show marshmallow`?

**Comment by Slach** [comment]
`pip3 show packaging` ?

**Comment by jerryjliu** [comment]
```
Name: packaging
Version: 21.3
Summary: Core utilities for Python packages
Home-page: https://github.com/pypa/packaging
Author: Donald Stufft and individual contributors
Author-email: donald@stufft.io
License: BSD-2-Clause or Apache-2.0
Location: /Users/jerryliu/Programming/gpt_index/.venv/lib/python3.8/site-packages
Requires: pyparsing
Required-by: transformers, QtPy, pytest, nbconvert, matplotlib, marshmallow, jupyterlab, jupyterlab-server, jupyter-server, ipykernel, huggingface-hub
```

**Comment by Slach** [comment]
sorry, it was my broken virtual environment

**Comment by Slach** [comment]
thanks for your great simple library
